model = "openai/gpt-5.1-codex-max"
model_provider = "cliproxyapi"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
web_search_request = true
network_access = true

[model_providers.openrouter]
name = "openrouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

[model_providers.cliproxyapi]
name = "cliproxyapi"
base_url = "http://127.0.0.1:8317/v1"
wire_api = "responses"
